//Action Types

//Action GPIT
export const GPIT_CONNECT = 'GPIT_CONNECT'
export const SET_GPIT_CONNECT_RESULT = 'SET_GPIT_CONNECT_RESULT'
export const SET_USER_ROLE = 'SET_USER_ROLE'
export const SET_NUDOSS_NUMBER = 'SET_NUDOSS_NUMBER'
export const SET_COLLABORATORS_NUDOSS = 'SET_COLLABORATORS'
export const SET_PERSONNAL_HISTORY = 'SET_PERSONNAL_HISTORY'
export const SET_COLLABORATORS_HISTORY = 'SET_COLLABORATORS_HISTORY'

export const INC_COUNTER = 'INC_COUNTER'
export const DEC_COUNTER = 'DEC_COUNTER'

//Header
export const SET_HEADER_HEIGHT = 'SET_HEADER_HEIGHT'
export const SET_HEADER_TAB = 'SET_HEADER_TAB'
export const SET_HEADER_NAME = 'SET_HEADER_NAME'
export const SET_STEPPER_NUMBER = 'SET_STEPPER_NUMBER'
export const SET_ALLOW_NOTIFICATIONS = 'SET_ALLOW_NOTIFICATIONS'

//Notification
export const SET_NOTIFICATIONS = 'SET_NOTIFICATIONS'
export const ADD_NOTIFICATION = 'ADD_NOTIFICATION'

//Connectivity
export const SET_CONNECTIVITY = 'SET_CONNECTIVITY'
